// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeSuggestions.Data;

#nullable disable

namespace TimeSuggestions.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807171308_AddIntegrityConstraints")]
    partial class AddIntegrityConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TimeSuggestions.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseNumber = "K-2026-001",
                            ClientName = "Kowalski",
                            IsActive = true,
                            Keywords = "",
                            Name = "Kowalski sp. z o.o. — obsługa korporacyjna"
                        },
                        new
                        {
                            Id = 2,
                            CaseNumber = "NT-2026-113",
                            ClientName = "NovaTech",
                            IsActive = true,
                            Keywords = "",
                            Name = "NovaTech S.A. — umowa wdrożeniowa"
                        },
                        new
                        {
                            Id = 3,
                            CaseNumber = "GZ-2026-007",
                            ClientName = "Grzegrzółka",
                            IsActive = true,
                            Keywords = "",
                            Name = "Spór Grzegrzółka vs Żółć"
                        },
                        new
                        {
                            Id = 4,
                            CaseNumber = "AB-2026-021",
                            ClientName = "Alfa Holding",
                            IsActive = true,
                            Keywords = "Alfa;Beta",
                            Name = "Fuzja Alfa/Beta"
                        },
                        new
                        {
                            Id = 5,
                            CaseNumber = "BL-2026-030",
                            ClientName = "Beta Logistics",
                            IsActive = true,
                            Keywords = "Beta",
                            Name = "Beta Logistics — audyt umów"
                        });
                });

            modelBuilder.Entity("TimeSuggestions.Models.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAmbiguous")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProposedDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("Source", "ExternalId", "EntryDate")
                        .IsUnique();

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("TimeSuggestions.Models.SyncRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedExisting")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncRuns");
                });

            modelBuilder.Entity("TimeSuggestions.Models.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreatedFromSuggestion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuggestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("SuggestionId")
                        .IsUnique();

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("TimeSuggestions.Models.Suggestion", b =>
                {
                    b.HasOne("TimeSuggestions.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("TimeSuggestions.Models.TimeEntry", b =>
                {
                    b.HasOne("TimeSuggestions.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeSuggestions.Models.Suggestion", "Suggestion")
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Suggestion");
                });
#pragma warning restore 612, 618
        }
    }
}
