// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeSuggestions.Data;

#nullable disable

namespace TimeSuggestions.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TimeSuggestions.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseNumber = "K-2026-001",
                            ClientName = "Kowalski",
                            IsActive = true,
                            Keywords = "",
                            Name = "Kowalski sp. z o.o. — obsługa korporacyjna"
                        },
                        new
                        {
                            Id = 2,
                            CaseNumber = "NT-2026-113",
                            ClientName = "NovaTech",
                            IsActive = true,
                            Keywords = "",
                            Name = "NovaTech S.A. — umowa wdrożeniowa"
                        },
                        new
                        {
                            Id = 3,
                            CaseNumber = "GZ-2026-007",
                            ClientName = "Grzegrzółka",
                            IsActive = true,
                            Keywords = "",
                            Name = "Spór Grzegrzółka vs Żółć"
                        },
                        new
                        {
                            Id = 4,
                            CaseNumber = "AB-2026-021",
                            ClientName = "Alfa Holding",
                            IsActive = true,
                            Keywords = "Alfa;Beta",
                            Name = "Fuzja Alfa/Beta"
                        },
                        new
                        {
                            Id = 5,
                            CaseNumber = "BL-2026-030",
                            ClientName = "Beta Logistics",
                            IsActive = true,
                            Keywords = "Beta",
                            Name = "Beta Logistics — audyt umów"
                        });
                });

            modelBuilder.Entity("TimeSuggestions.Models.DocumentActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId", "VersionId", "OccurredAt")
                        .IsUnique();

                    b.ToTable("DocumentActivities");
                });

            modelBuilder.Entity("TimeSuggestions.Models.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedGapsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAmbiguous")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserAdjusted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsTimeReview")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProposedDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionAnchor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("TimeEntryId");

                    b.HasIndex("Source", "ExternalId", "SessionAnchor")
                        .IsUnique();

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("TimeSuggestions.Models.SyncRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedExisting")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncRuns");
                });

            modelBuilder.Entity("TimeSuggestions.Models.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreatedFromSuggestion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedGapsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAt");

                    b.HasIndex("CaseId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("TimeSuggestions.Models.TimeEntryAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GapEndAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GapStartAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimeEntryId");

                    b.ToTable("TimeEntryAdjustments");
                });

            modelBuilder.Entity("TimeSuggestions.Models.Suggestion", b =>
                {
                    b.HasOne("TimeSuggestions.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId");

                    b.HasOne("TimeSuggestions.Models.TimeEntry", "TimeEntry")
                        .WithMany("Suggestions")
                        .HasForeignKey("TimeEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Case");

                    b.Navigation("TimeEntry");
                });

            modelBuilder.Entity("TimeSuggestions.Models.TimeEntry", b =>
                {
                    b.HasOne("TimeSuggestions.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("TimeSuggestions.Models.TimeEntryAdjustment", b =>
                {
                    b.HasOne("TimeSuggestions.Models.TimeEntry", "TimeEntry")
                        .WithMany("Adjustments")
                        .HasForeignKey("TimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeEntry");
                });

            modelBuilder.Entity("TimeSuggestions.Models.TimeEntry", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
